version: "1"
services:
  app:
    container_name: timetracker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/time-tracker-app?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=lhs22LI=D=
    ports:
      - '8080:8080'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lhs22LI=D=
      - POSTGRES_DB=time-tracker-app
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

