spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time-tracker-app
    username: postgres
    password: lhs22LI=D=
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
